// <auto-generated />
using System;
using BeFeira.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeFeira.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230113001537_inital")]
    partial class inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeFeira.Shared.Administrador", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Administrador");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Createdat = new DateTime(2023, 1, 13, 0, 15, 37, 171, DateTimeKind.Local).AddTicks(2193),
                            Password = "1234",
                            Updatedat = new DateTime(2023, 1, 13, 0, 15, 37, 171, DateTimeKind.Local).AddTicks(2243),
                            Username = "Bernas"
                        },
                        new
                        {
                            ID = 2,
                            Createdat = new DateTime(2023, 1, 13, 0, 15, 37, 171, DateTimeKind.Local).AddTicks(2247),
                            Password = "2345",
                            Updatedat = new DateTime(2023, 1, 13, 0, 15, 37, 171, DateTimeKind.Local).AddTicks(2248),
                            Username = "Cebolinha"
                        },
                        new
                        {
                            ID = 3,
                            Createdat = new DateTime(2023, 1, 13, 0, 15, 37, 171, DateTimeKind.Local).AddTicks(2250),
                            Password = "3456",
                            Updatedat = new DateTime(2023, 1, 13, 0, 15, 37, 171, DateTimeKind.Local).AddTicks(2251),
                            Username = "Sergio"
                        },
                        new
                        {
                            ID = 4,
                            Createdat = new DateTime(2023, 1, 13, 0, 15, 37, 171, DateTimeKind.Local).AddTicks(2253),
                            Password = "1134",
                            Updatedat = new DateTime(2023, 1, 13, 0, 15, 37, 171, DateTimeKind.Local).AddTicks(2254),
                            Username = "Anastásia"
                        },
                        new
                        {
                            ID = 5,
                            Createdat = new DateTime(2023, 1, 13, 0, 15, 37, 171, DateTimeKind.Local).AddTicks(2256),
                            Password = "2245",
                            Updatedat = new DateTime(2023, 1, 13, 0, 15, 37, 171, DateTimeKind.Local).AddTicks(2257),
                            Username = "Rodri"
                        },
                        new
                        {
                            ID = 6,
                            Createdat = new DateTime(2023, 1, 13, 0, 15, 37, 171, DateTimeKind.Local).AddTicks(2258),
                            Password = "3453",
                            Updatedat = new DateTime(2023, 1, 13, 0, 15, 37, 171, DateTimeKind.Local).AddTicks(2259),
                            Username = "Jairzinho"
                        });
                });

            modelBuilder.Entity("BeFeira.Shared.Carrinho", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ClienteID")
                        .HasColumnType("int");

                    b.Property<int>("StandID")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("ClienteID");

                    b.HasIndex("StandID");

                    b.ToTable("Carrinho");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ClienteID = 1,
                            StandID = 1,
                            Total = 0m
                        },
                        new
                        {
                            ID = 2,
                            ClienteID = 2,
                            StandID = 2,
                            Total = 10m
                        },
                        new
                        {
                            ID = 3,
                            ClienteID = 3,
                            StandID = 3,
                            Total = 5m
                        });
                });

            modelBuilder.Entity("BeFeira.Shared.CarrinhoProduto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CarrinhoID")
                        .HasColumnType("int");

                    b.Property<float>("Preco")
                        .HasColumnType("real");

                    b.Property<int?>("ProdutoID")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("TaxaBefeira")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CarrinhoID");

                    b.HasIndex("ProdutoID");

                    b.ToTable("CarrinhoProduto");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CarrinhoID = 1,
                            Preco = 10f,
                            ProdutoID = 1,
                            Quantidade = 1,
                            TaxaBefeira = 10
                        },
                        new
                        {
                            ID = 2,
                            CarrinhoID = 2,
                            Preco = 120f,
                            ProdutoID = 2,
                            Quantidade = 4,
                            TaxaBefeira = 10
                        },
                        new
                        {
                            ID = 3,
                            CarrinhoID = 3,
                            Preco = 22f,
                            ProdutoID = 3,
                            Quantidade = 2,
                            TaxaBefeira = 10
                        });
                });

            modelBuilder.Entity("BeFeira.Shared.Cliente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "a1@uminho.pt",
                            Password = "sporting",
                            Username = "Pedro"
                        },
                        new
                        {
                            ID = 2,
                            Email = "a2@uminho.pt",
                            Password = "benfica",
                            Username = "João"
                        },
                        new
                        {
                            ID = 3,
                            Email = "a3@uminho.pt",
                            Password = "porto",
                            Username = "Zé"
                        },
                        new
                        {
                            ID = 4,
                            Email = "a4@uminho.pt",
                            Password = "sporting11",
                            Username = "Ana"
                        },
                        new
                        {
                            ID = 5,
                            Email = "a5@uminho.pt",
                            Password = "benfica11",
                            Username = "Ivo"
                        },
                        new
                        {
                            ID = 6,
                            Email = "a6@uminho.pt",
                            Password = "porto11",
                            Username = "Nestor"
                        },
                        new
                        {
                            ID = 7,
                            Email = "a7@uminho.pt",
                            Password = "sporting22",
                            Username = "Paulo"
                        },
                        new
                        {
                            ID = 8,
                            Email = "a8@uminho.pt",
                            Password = "benfica22",
                            Username = "Bruno"
                        },
                        new
                        {
                            ID = 9,
                            Email = "a9@uminho.pt",
                            Password = "porto22",
                            Username = "Rui"
                        },
                        new
                        {
                            ID = 10,
                            Email = "a10@uminho.pt",
                            Password = "sporting33",
                            Username = "Francisca"
                        },
                        new
                        {
                            ID = 11,
                            Email = "a11@uminho.pt",
                            Password = "benfica33",
                            Username = "Patricia"
                        },
                        new
                        {
                            ID = 12,
                            Email = "a12@uminho.pt",
                            Password = "porto33",
                            Username = "Luis"
                        });
                });

            modelBuilder.Entity("BeFeira.Shared.Feira", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Feira");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Categoria = "Casa e Decoração"
                        },
                        new
                        {
                            ID = 2,
                            Categoria = "Animais"
                        },
                        new
                        {
                            ID = 3,
                            Categoria = "Mercearia e Produtos Frescos"
                        },
                        new
                        {
                            ID = 4,
                            Categoria = "Cultura"
                        },
                        new
                        {
                            ID = 5,
                            Categoria = "Véiculos"
                        },
                        new
                        {
                            ID = 6,
                            Categoria = "Escritório"
                        },
                        new
                        {
                            ID = 7,
                            Categoria = "Moda"
                        },
                        new
                        {
                            ID = 8,
                            Categoria = "Bricolagem"
                        },
                        new
                        {
                            ID = 9,
                            Categoria = "Animais de Estimação"
                        },
                        new
                        {
                            ID = 10,
                            Categoria = "Brinquedos"
                        },
                        new
                        {
                            ID = 11,
                            Categoria = "Gaming"
                        },
                        new
                        {
                            ID = 12,
                            Categoria = "Lazer"
                        },
                        new
                        {
                            ID = 13,
                            Categoria = "Saúde"
                        },
                        new
                        {
                            ID = 14,
                            Categoria = "Beleza"
                        },
                        new
                        {
                            ID = 15,
                            Categoria = "Eletrodomésticos"
                        },
                        new
                        {
                            ID = 16,
                            Categoria = "Imagem"
                        },
                        new
                        {
                            ID = 17,
                            Categoria = "Som"
                        },
                        new
                        {
                            ID = 18,
                            Categoria = "Smartphones e Acessórios"
                        },
                        new
                        {
                            ID = 19,
                            Categoria = "Informática"
                        },
                        new
                        {
                            ID = 20,
                            Categoria = "Desporto"
                        },
                        new
                        {
                            ID = 21,
                            Categoria = "Random"
                        });
                });

            modelBuilder.Entity("BeFeira.Shared.Produto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nome_Produto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Preco")
                        .HasColumnType("real");

                    b.Property<int>("Promocao")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("StandID")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int?>("SubCategoriaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StandID");

                    b.HasIndex("SubCategoriaID");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            NomeProduto = "Maçãs",
                            Preco = 2.9f,
                            Promocao = 0,
                            Rating = 4,
                            StandID = 1,
                            Stock = 3,
                            SubCategoriaID = 1
                        },
                        new
                        {
                            ID = 2,
                            NomeProduto = "Bonecos",
                            Preco = 25.9f,
                            Promocao = 0,
                            Rating = 2,
                            StandID = 2,
                            Stock = 2,
                            SubCategoriaID = 2
                        },
                        new
                        {
                            ID = 3,
                            NomeProduto = "Tapetea",
                            Preco = 23.9f,
                            Promocao = 0,
                            Rating = 3,
                            StandID = 3,
                            Stock = 1,
                            SubCategoriaID = 2
                        },
                        new
                        {
                            ID = 4,
                            NomeProduto = "Celular",
                            Preco = 299.9f,
                            Promocao = 0,
                            Rating = 5,
                            StandID = 4,
                            Stock = 20,
                            SubCategoriaID = 3
                        },
                        new
                        {
                            ID = 5,
                            NomeProduto = "Livro",
                            Preco = 15.99f,
                            Promocao = 0,
                            Rating = 4,
                            StandID = 5,
                            Stock = 15,
                            SubCategoriaID = 4
                        },
                        new
                        {
                            ID = 6,
                            NomeProduto = "Caneca",
                            Preco = 9.99f,
                            Promocao = 0,
                            Rating = 3,
                            StandID = 6,
                            Stock = 5,
                            SubCategoriaID = 5
                        },
                        new
                        {
                            ID = 7,
                            NomeProduto = "Bola de futebol",
                            Preco = 29.99f,
                            Promocao = 0,
                            Rating = 4,
                            StandID = 7,
                            Stock = 10,
                            SubCategoriaID = 6
                        },
                        new
                        {
                            ID = 8,
                            NomeProduto = "Perfume",
                            Preco = 69.99f,
                            Promocao = 0,
                            Rating = 5,
                            StandID = 8,
                            Stock = 7,
                            SubCategoriaID = 7
                        },
                        new
                        {
                            ID = 9,
                            NomeProduto = "Mala",
                            Preco = 99.99f,
                            Promocao = 0,
                            Rating = 2,
                            StandID = 9,
                            Stock = 3,
                            SubCategoriaID = 8
                        },
                        new
                        {
                            ID = 10,
                            NomeProduto = "Sapatos",
                            Preco = 89.99f,
                            Promocao = 0,
                            Rating = 4,
                            StandID = 10,
                            Stock = 5,
                            SubCategoriaID = 9
                        },
                        new
                        {
                            ID = 11,
                            NomeProduto = "Smartwatch",
                            Preco = 199.99f,
                            Promocao = 0,
                            Rating = 5,
                            StandID = 11,
                            Stock = 8,
                            SubCategoriaID = 10
                        },
                        new
                        {
                            ID = 12,
                            NomeProduto = "Fritadeira",
                            Preco = 49.99f,
                            Promocao = 0,
                            Rating = 3,
                            StandID = 12,
                            Stock = 4,
                            SubCategoriaID = 11
                        },
                        new
                        {
                            ID = 13,
                            NomeProduto = "Cadeira gamer",
                            Preco = 129.99f,
                            Promocao = 0,
                            Rating = 4,
                            StandID = 13,
                            Stock = 2,
                            SubCategoriaID = 12
                        },
                        new
                        {
                            ID = 14,
                            NomeProduto = "Bicicleta",
                            Preco = 399.99f,
                            Promocao = 0,
                            Rating = 5,
                            StandID = 14,
                            Stock = 6,
                            SubCategoriaID = 13
                        },
                        new
                        {
                            ID = 15,
                            NomeProduto = "Aspirador",
                            Preco = 99.99f,
                            Promocao = 0,
                            Rating = 4,
                            StandID = 15,
                            Stock = 8,
                            SubCategoriaID = 14
                        },
                        new
                        {
                            ID = 16,
                            NomeProduto = "Toalhas de banho",
                            Preco = 12.9f,
                            Promocao = 0,
                            Rating = 5,
                            StandID = 1,
                            Stock = 7,
                            SubCategoriaID = 1
                        },
                        new
                        {
                            ID = 17,
                            NomeProduto = "Ração para frangos",
                            Preco = 3.9f,
                            Promocao = 0,
                            Rating = 4,
                            StandID = 2,
                            Stock = 6,
                            SubCategoriaID = 4
                        },
                        new
                        {
                            ID = 18,
                            NomeProduto = "Carnes de porco",
                            Preco = 15.9f,
                            Promocao = 0,
                            Rating = 4,
                            StandID = 3,
                            Stock = 10,
                            SubCategoriaID = 8
                        },
                        new
                        {
                            ID = 19,
                            NomeProduto = "Livro de terror",
                            Preco = 8.9f,
                            Promocao = 0,
                            Rating = 3,
                            StandID = 4,
                            Stock = 5,
                            SubCategoriaID = 10
                        },
                        new
                        {
                            ID = 20,
                            NomeProduto = "BMW elétrico",
                            Preco = 65000f,
                            Promocao = 0,
                            Rating = 5,
                            StandID = 5,
                            Stock = 2,
                            SubCategoriaID = 13
                        },
                        new
                        {
                            ID = 21,
                            NomeProduto = "Mesa de escritório",
                            Preco = 150f,
                            Promocao = 0,
                            Rating = 4,
                            StandID = 6,
                            Stock = 4,
                            SubCategoriaID = 16
                        },
                        new
                        {
                            ID = 22,
                            NomeProduto = "Camisola para homem",
                            Preco = 25f,
                            Promocao = 0,
                            Rating = 5,
                            StandID = 7,
                            Stock = 10,
                            SubCategoriaID = 19
                        },
                        new
                        {
                            ID = 23,
                            NomeProduto = "Serra circular",
                            Preco = 150f,
                            Promocao = 0,
                            Rating = 4,
                            StandID = 8,
                            Stock = 3,
                            SubCategoriaID = 21
                        },
                        new
                        {
                            ID = 24,
                            NomeProduto = "Ração para cães",
                            Preco = 12.9f,
                            Promocao = 0,
                            Rating = 5,
                            StandID = 9,
                            Stock = 8,
                            SubCategoriaID = 23
                        },
                        new
                        {
                            ID = 25,
                            NomeProduto = "Toalhas de banho",
                            Preco = 15.99f,
                            Promocao = 0,
                            Rating = 4,
                            StandID = 1,
                            Stock = 10,
                            SubCategoriaID = 1
                        },
                        new
                        {
                            ID = 26,
                            NomeProduto = "Móveis de jardim",
                            Preco = 299.99f,
                            Promocao = 0,
                            Rating = 4,
                            StandID = 2,
                            Stock = 5,
                            SubCategoriaID = 2
                        },
                        new
                        {
                            ID = 27,
                            NomeProduto = "Eletrodomésticos de cozinha",
                            Preco = 399.99f,
                            Promocao = 0,
                            Rating = 5,
                            StandID = 3,
                            Stock = 3,
                            SubCategoriaID = 3
                        },
                        new
                        {
                            ID = 28,
                            NomeProduto = "Ração para cães",
                            Preco = 9.99f,
                            Promocao = 0,
                            Rating = 4,
                            StandID = 4,
                            Stock = 20,
                            SubCategoriaID = 4
                        },
                        new
                        {
                            ID = 29,
                            NomeProduto = "Frangos orgânicos",
                            Preco = 7.99f,
                            Promocao = 0,
                            Rating = 5,
                            StandID = 5,
                            Stock = 15,
                            SubCategoriaID = 5
                        });
                });

            modelBuilder.Entity("BeFeira.Shared.Promocao", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Desconto")
                        .HasColumnType("int");

                    b.Property<int?>("ProdutoID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProdutoID");

                    b.ToTable("Promocao");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Date = new DateTime(2023, 1, 13, 0, 15, 37, 171, DateTimeKind.Local).AddTicks(2655),
                            Desconto = 10,
                            ProdutoID = 1
                        });
                });

            modelBuilder.Entity("BeFeira.Shared.Stand", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("FeiraID")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VendedorID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FeiraID");

                    b.HasIndex("VendedorID");

                    b.ToTable("Stand");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FeiraID = 1,
                            Nome = "ZaraHome",
                            VendedorID = 1
                        },
                        new
                        {
                            ID = 2,
                            FeiraID = 2,
                            Nome = "Agriloja",
                            VendedorID = 5
                        },
                        new
                        {
                            ID = 3,
                            FeiraID = 3,
                            Nome = "Pingo Doce",
                            VendedorID = 1
                        },
                        new
                        {
                            ID = 4,
                            FeiraID = 4,
                            Nome = "Bertrand",
                            VendedorID = 3
                        },
                        new
                        {
                            ID = 5,
                            FeiraID = 5,
                            Nome = "BMW",
                            VendedorID = 4
                        },
                        new
                        {
                            ID = 6,
                            FeiraID = 6,
                            Nome = "IKEA",
                            VendedorID = 1
                        },
                        new
                        {
                            ID = 7,
                            FeiraID = 7,
                            Nome = "Zara",
                            VendedorID = 1
                        },
                        new
                        {
                            ID = 8,
                            FeiraID = 8,
                            Nome = "Leroy Merlin",
                            VendedorID = 1
                        },
                        new
                        {
                            ID = 9,
                            FeiraID = 9,
                            Nome = "Animais e Companhia",
                            VendedorID = 1
                        },
                        new
                        {
                            ID = 10,
                            FeiraID = 10,
                            Nome = "ToysRus",
                            VendedorID = 1
                        },
                        new
                        {
                            ID = 11,
                            FeiraID = 11,
                            Nome = "CEX",
                            VendedorID = 5
                        },
                        new
                        {
                            ID = 12,
                            FeiraID = 12,
                            Nome = "Worten",
                            VendedorID = 5
                        },
                        new
                        {
                            ID = 13,
                            FeiraID = 13,
                            Nome = "WELLS",
                            VendedorID = 2
                        },
                        new
                        {
                            ID = 14,
                            FeiraID = 14,
                            Nome = "Perfumes e Companhia",
                            VendedorID = 1
                        },
                        new
                        {
                            ID = 15,
                            FeiraID = 15,
                            Nome = "Tien21",
                            VendedorID = 1
                        },
                        new
                        {
                            ID = 16,
                            FeiraID = 16,
                            Nome = "Canon",
                            VendedorID = 2
                        },
                        new
                        {
                            ID = 17,
                            FeiraID = 17,
                            Nome = "JBL",
                            VendedorID = 6
                        },
                        new
                        {
                            ID = 18,
                            FeiraID = 18,
                            Nome = "WortenMobile",
                            VendedorID = 1
                        },
                        new
                        {
                            ID = 19,
                            FeiraID = 19,
                            Nome = "PCDiga",
                            VendedorID = 2
                        },
                        new
                        {
                            ID = 20,
                            FeiraID = 20,
                            Nome = "SoloPorteros",
                            VendedorID = 6
                        },
                        new
                        {
                            ID = 21,
                            FeiraID = 21,
                            Nome = "Pilhas e Companhia",
                            VendedorID = 1
                        },
                        new
                        {
                            ID = 22,
                            FeiraID = 1,
                            Nome = "Casa da Cama",
                            VendedorID = 6
                        },
                        new
                        {
                            ID = 23,
                            FeiraID = 2,
                            Nome = "Quinta Lagares",
                            VendedorID = 2
                        },
                        new
                        {
                            ID = 24,
                            FeiraID = 3,
                            Nome = "Mercado Central",
                            VendedorID = 3
                        },
                        new
                        {
                            ID = 25,
                            FeiraID = 4,
                            Nome = "Livraria Santos",
                            VendedorID = 3
                        },
                        new
                        {
                            ID = 26,
                            FeiraID = 5,
                            Nome = "Mercedes",
                            VendedorID = 2
                        },
                        new
                        {
                            ID = 27,
                            FeiraID = 6,
                            Nome = "Papelaria Tavares",
                            VendedorID = 1
                        },
                        new
                        {
                            ID = 28,
                            FeiraID = 7,
                            Nome = "H&M",
                            VendedorID = 1
                        },
                        new
                        {
                            ID = 29,
                            FeiraID = 8,
                            Nome = "Ferra&Solda",
                            VendedorID = 2
                        },
                        new
                        {
                            ID = 30,
                            FeiraID = 9,
                            Nome = "Pet Store",
                            VendedorID = 1
                        },
                        new
                        {
                            ID = 31,
                            FeiraID = 10,
                            Nome = "Toys",
                            VendedorID = 2
                        },
                        new
                        {
                            ID = 32,
                            FeiraID = 11,
                            Nome = "Joguinhos",
                            VendedorID = 5
                        },
                        new
                        {
                            ID = 33,
                            FeiraID = 12,
                            Nome = "Escuta e Acampa",
                            VendedorID = 1
                        },
                        new
                        {
                            ID = 34,
                            FeiraID = 13,
                            Nome = "Farmácia Loures",
                            VendedorID = 6
                        },
                        new
                        {
                            ID = 35,
                            FeiraID = 14,
                            Nome = "Perfumaria Bela",
                            VendedorID = 1
                        },
                        new
                        {
                            ID = 36,
                            FeiraID = 15,
                            Nome = "EletroTec",
                            VendedorID = 1
                        },
                        new
                        {
                            ID = 37,
                            FeiraID = 16,
                            Nome = "Loja de Fotografia",
                            VendedorID = 2
                        },
                        new
                        {
                            ID = 38,
                            FeiraID = 17,
                            Nome = "TecSom",
                            VendedorID = 8
                        },
                        new
                        {
                            ID = 39,
                            FeiraID = 18,
                            Nome = "Pc Componentes",
                            VendedorID = 7
                        },
                        new
                        {
                            ID = 40,
                            FeiraID = 19,
                            Nome = "InfoTec",
                            VendedorID = 2
                        },
                        new
                        {
                            ID = 41,
                            FeiraID = 20,
                            Nome = "Decatlon",
                            VendedorID = 7
                        },
                        new
                        {
                            ID = 42,
                            FeiraID = 21,
                            Nome = "Brindes",
                            VendedorID = 2
                        },
                        new
                        {
                            ID = 43,
                            FeiraID = 1,
                            Nome = "Loja de Jardinagem",
                            VendedorID = 1
                        },
                        new
                        {
                            ID = 44,
                            FeiraID = 2,
                            Nome = "Petshoping",
                            VendedorID = 2
                        },
                        new
                        {
                            ID = 45,
                            FeiraID = 3,
                            Nome = "Feira Orgânica",
                            VendedorID = 7
                        },
                        new
                        {
                            ID = 46,
                            FeiraID = 4,
                            Nome = "Livraria Souza",
                            VendedorID = 6
                        },
                        new
                        {
                            ID = 47,
                            FeiraID = 5,
                            Nome = "Fiat",
                            VendedorID = 2
                        },
                        new
                        {
                            ID = 48,
                            FeiraID = 6,
                            Nome = "Papelaria artesanal",
                            VendedorID = 1
                        },
                        new
                        {
                            ID = 49,
                            FeiraID = 7,
                            Nome = "Pull & Bear",
                            VendedorID = 3
                        },
                        new
                        {
                            ID = 50,
                            FeiraID = 8,
                            Nome = "FerraForte",
                            VendedorID = 3
                        },
                        new
                        {
                            ID = 51,
                            FeiraID = 9,
                            Nome = "Pet&Comp",
                            VendedorID = 3
                        },
                        new
                        {
                            ID = 52,
                            FeiraID = 10,
                            Nome = "Brincadeiras",
                            VendedorID = 2
                        },
                        new
                        {
                            ID = 53,
                            FeiraID = 11,
                            Nome = "Loja de jogos digitais",
                            VendedorID = 1
                        },
                        new
                        {
                            ID = 54,
                            FeiraID = 12,
                            Nome = "Puzzle Master",
                            VendedorID = 3
                        },
                        new
                        {
                            ID = 55,
                            FeiraID = 13,
                            Nome = "Farmácia natural",
                            VendedorID = 2
                        },
                        new
                        {
                            ID = 56,
                            FeiraID = 14,
                            Nome = "Perfumaria artesanal",
                            VendedorID = 1
                        },
                        new
                        {
                            ID = 57,
                            FeiraID = 15,
                            Nome = "EletroFine",
                            VendedorID = 3
                        },
                        new
                        {
                            ID = 58,
                            FeiraID = 16,
                            Nome = "Loja de Fotografia profissional",
                            VendedorID = 2
                        },
                        new
                        {
                            ID = 59,
                            FeiraID = 17,
                            Nome = "Loja de Som",
                            VendedorID = 4
                        },
                        new
                        {
                            ID = 60,
                            FeiraID = 18,
                            Nome = "TelePersona",
                            VendedorID = 4
                        },
                        new
                        {
                            ID = 61,
                            FeiraID = 19,
                            Nome = "InformaTic",
                            VendedorID = 2
                        },
                        new
                        {
                            ID = 62,
                            FeiraID = 20,
                            Nome = "Loja de desportos radicais",
                            VendedorID = 8
                        },
                        new
                        {
                            ID = 63,
                            FeiraID = 21,
                            Nome = "Loja dos trezentos",
                            VendedorID = 4
                        });
                });

            modelBuilder.Entity("BeFeira.Shared.Subcategoria", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StandID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StandID");

                    b.ToTable("Subcategoria");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Descricao = "Casa de Banho",
                            StandID = 1
                        },
                        new
                        {
                            ID = 2,
                            Descricao = "Sala",
                            StandID = 1
                        },
                        new
                        {
                            ID = 3,
                            Descricao = "Cozinha",
                            StandID = 1
                        },
                        new
                        {
                            ID = 4,
                            Descricao = "Rações",
                            StandID = 2
                        },
                        new
                        {
                            ID = 5,
                            Descricao = "Frangos",
                            StandID = 2
                        },
                        new
                        {
                            ID = 6,
                            Descricao = "Coelhos",
                            StandID = 2
                        },
                        new
                        {
                            ID = 7,
                            Descricao = "Higiene",
                            StandID = 3
                        },
                        new
                        {
                            ID = 8,
                            Descricao = "Talho",
                            StandID = 3
                        },
                        new
                        {
                            ID = 9,
                            Descricao = "Peixaria",
                            StandID = 3
                        },
                        new
                        {
                            ID = 10,
                            Descricao = "Terror",
                            StandID = 4
                        },
                        new
                        {
                            ID = 11,
                            Descricao = "Comédia",
                            StandID = 4
                        },
                        new
                        {
                            ID = 12,
                            Descricao = "Romance",
                            StandID = 4
                        },
                        new
                        {
                            ID = 13,
                            Descricao = "Elétricos",
                            StandID = 5
                        },
                        new
                        {
                            ID = 14,
                            Descricao = "Gasóleo",
                            StandID = 5
                        },
                        new
                        {
                            ID = 15,
                            Descricao = "Hibrídos",
                            StandID = 5
                        },
                        new
                        {
                            ID = 16,
                            Descricao = "Secretárias",
                            StandID = 6
                        },
                        new
                        {
                            ID = 17,
                            Descricao = "Tapetes",
                            StandID = 6
                        },
                        new
                        {
                            ID = 18,
                            Descricao = "Cadeiras",
                            StandID = 6
                        },
                        new
                        {
                            ID = 19,
                            Descricao = "Vestuário Masculino",
                            StandID = 7
                        },
                        new
                        {
                            ID = 20,
                            Descricao = "Vestuário Feminino",
                            StandID = 7
                        },
                        new
                        {
                            ID = 21,
                            Descricao = "Ferramentas Elétricas",
                            StandID = 8
                        },
                        new
                        {
                            ID = 22,
                            Descricao = "Ferramentas Manuais",
                            StandID = 8
                        },
                        new
                        {
                            ID = 23,
                            Descricao = "Cães",
                            StandID = 9
                        },
                        new
                        {
                            ID = 24,
                            Descricao = "Gatos",
                            StandID = 9
                        },
                        new
                        {
                            ID = 25,
                            Descricao = "Brinquedos para crianças",
                            StandID = 10
                        },
                        new
                        {
                            ID = 26,
                            Descricao = "Jogos de tabuleiro",
                            StandID = 10
                        },
                        new
                        {
                            ID = 27,
                            Descricao = "Consolas",
                            StandID = 11
                        },
                        new
                        {
                            ID = 28,
                            Descricao = "Jogos",
                            StandID = 11
                        },
                        new
                        {
                            ID = 29,
                            Descricao = "Bicicletas",
                            StandID = 12
                        },
                        new
                        {
                            ID = 30,
                            Descricao = "Pesca",
                            StandID = 12
                        },
                        new
                        {
                            ID = 31,
                            Descricao = "Remédios naturais",
                            StandID = 13
                        },
                        new
                        {
                            ID = 32,
                            Descricao = "Produtos de beleza",
                            StandID = 14
                        },
                        new
                        {
                            ID = 33,
                            Descricao = "Máquinas de lavar",
                            StandID = 15
                        },
                        new
                        {
                            ID = 34,
                            Descricao = "Fogões",
                            StandID = 15
                        },
                        new
                        {
                            ID = 35,
                            Descricao = "Câmaras",
                            StandID = 16
                        },
                        new
                        {
                            ID = 36,
                            Descricao = "Lentes",
                            StandID = 16
                        },
                        new
                        {
                            ID = 37,
                            Descricao = "Colunas",
                            StandID = 17
                        },
                        new
                        {
                            ID = 38,
                            Descricao = "Microfones",
                            StandID = 17
                        },
                        new
                        {
                            ID = 39,
                            Descricao = "Smartphones",
                            StandID = 18
                        },
                        new
                        {
                            ID = 40,
                            Descricao = "Acessórios para smartphones",
                            StandID = 18
                        },
                        new
                        {
                            ID = 41,
                            Descricao = "Computadores",
                            StandID = 19
                        },
                        new
                        {
                            ID = 42,
                            Descricao = "Periféricos",
                            StandID = 19
                        },
                        new
                        {
                            ID = 43,
                            Descricao = "Running",
                            StandID = 20
                        },
                        new
                        {
                            ID = 44,
                            Descricao = "Fitness",
                            StandID = 20
                        },
                        new
                        {
                            ID = 45,
                            Descricao = "Cozinha",
                            StandID = 21
                        },
                        new
                        {
                            ID = 46,
                            Descricao = "Decoração interior",
                            StandID = 21
                        },
                        new
                        {
                            ID = 47,
                            Descricao = "Toalhas de banho",
                            StandID = 1
                        },
                        new
                        {
                            ID = 48,
                            Descricao = "Camas",
                            StandID = 1
                        },
                        new
                        {
                            ID = 49,
                            Descricao = "Utensílios de cozinha",
                            StandID = 3
                        },
                        new
                        {
                            ID = 50,
                            Descricao = "Artigos para animais exóticos",
                            StandID = 2
                        },
                        new
                        {
                            ID = 51,
                            Descricao = "Artigos para equinos",
                            StandID = 2
                        },
                        new
                        {
                            ID = 52,
                            Descricao = "Alimentos congelados",
                            StandID = 3
                        },
                        new
                        {
                            ID = 53,
                            Descricao = "Artigos de papelaria",
                            StandID = 4
                        },
                        new
                        {
                            ID = 54,
                            Descricao = "Artigos de arte",
                            StandID = 4
                        },
                        new
                        {
                            ID = 55,
                            Descricao = "Motos",
                            StandID = 5
                        },
                        new
                        {
                            ID = 56,
                            Descricao = "Carros Usados",
                            StandID = 5
                        },
                        new
                        {
                            ID = 57,
                            Descricao = "Carros Novos",
                            StandID = 5
                        },
                        new
                        {
                            ID = 58,
                            Descricao = "Material Escritório",
                            StandID = 6
                        },
                        new
                        {
                            ID = 59,
                            Descricao = "Material Escolar",
                            StandID = 6
                        },
                        new
                        {
                            ID = 60,
                            Descricao = "Acessórios de Moda",
                            StandID = 7
                        },
                        new
                        {
                            ID = 61,
                            Descricao = "Material de Costura",
                            StandID = 7
                        },
                        new
                        {
                            ID = 62,
                            Descricao = "Pintura e Revestimento",
                            StandID = 8
                        },
                        new
                        {
                            ID = 63,
                            Descricao = "Material Elétrico",
                            StandID = 8
                        },
                        new
                        {
                            ID = 64,
                            Descricao = "Roupas e Acessórios para animais",
                            StandID = 9
                        },
                        new
                        {
                            ID = 65,
                            Descricao = "Recém-nascidos",
                            StandID = 10
                        },
                        new
                        {
                            ID = 66,
                            Descricao = "Realidade virtual",
                            StandID = 11
                        },
                        new
                        {
                            ID = 67,
                            Descricao = "RPG",
                            StandID = 11
                        },
                        new
                        {
                            ID = 68,
                            Descricao = "Camping",
                            StandID = 12
                        },
                        new
                        {
                            ID = 69,
                            Descricao = "Mochilas e equipamentos",
                            StandID = 12
                        },
                        new
                        {
                            ID = 70,
                            Descricao = "Produtos orgânicos",
                            StandID = 13
                        },
                        new
                        {
                            ID = 71,
                            Descricao = "Cosméticos",
                            StandID = 14
                        },
                        new
                        {
                            ID = 72,
                            Descricao = "Eletrodomésticos de cozinha",
                            StandID = 15
                        },
                        new
                        {
                            ID = 73,
                            Descricao = "Eletrodomésticos de limpeza",
                            StandID = 15
                        });
                });

            modelBuilder.Entity("BeFeira.Shared.Venda", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CarrinhoID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<float>("Total")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.HasIndex("CarrinhoID");

                    b.ToTable("Venda");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CarrinhoID = 1,
                            Date = new DateTime(2023, 1, 13, 0, 15, 37, 171, DateTimeKind.Local).AddTicks(2702),
                            Total = 0f
                        },
                        new
                        {
                            ID = 2,
                            CarrinhoID = 2,
                            Date = new DateTime(2023, 1, 13, 0, 15, 37, 171, DateTimeKind.Local).AddTicks(2705),
                            Total = 0f
                        });
                });

            modelBuilder.Entity("BeFeira.Shared.VendaProduto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<float>("Preco")
                        .HasColumnType("real");

                    b.Property<int?>("ProdutoID")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("TaxaBefeira")
                        .HasColumnType("int");

                    b.Property<int?>("VendaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProdutoID");

                    b.HasIndex("VendaID");

                    b.ToTable("VendaProduto");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Preco = 10f,
                            ProdutoID = 1,
                            Quantidade = 2,
                            TaxaBefeira = 10,
                            VendaID = 1
                        },
                        new
                        {
                            ID = 2,
                            Preco = 20f,
                            ProdutoID = 3,
                            Quantidade = 3,
                            TaxaBefeira = 10,
                            VendaID = 2
                        });
                });

            modelBuilder.Entity("BeFeira.Shared.Vendedor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mbway")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Vendedor");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "a13@uminho.pt",
                            Iban = "1113231",
                            Mbway = "964888999",
                            Password = "0040",
                            Rating = 9,
                            Username = "Lucas"
                        },
                        new
                        {
                            ID = 2,
                            Email = "a14@uminho.pt",
                            Iban = "3453661",
                            Mbway = "972822895",
                            Password = "0181",
                            Rating = 6,
                            Username = "Jonny"
                        },
                        new
                        {
                            ID = 3,
                            Email = "a15@uminho.pt",
                            Iban = "8142831",
                            Mbway = "964457999",
                            Password = "2030",
                            Rating = 7,
                            Username = "Ema"
                        },
                        new
                        {
                            ID = 4,
                            Email = "a16@uminho.pt",
                            Iban = "7403061",
                            Mbway = "932823894",
                            Password = "1161",
                            Rating = 8,
                            Username = "Diana"
                        },
                        new
                        {
                            ID = 5,
                            Email = "a17@uminho.pt",
                            Iban = "1213221",
                            Mbway = "925679969",
                            Password = "0340",
                            Rating = 9,
                            Username = "Jordi Alba"
                        },
                        new
                        {
                            ID = 6,
                            Email = "a18@uminho.pt",
                            Iban = "5333161",
                            Mbway = "923852594",
                            Password = "8481",
                            Rating = 2,
                            Username = "Marcelo"
                        },
                        new
                        {
                            ID = 7,
                            Email = "a19@uminho.pt",
                            Iban = "0102831",
                            Mbway = "964646797",
                            Password = "9039",
                            Rating = 5,
                            Username = "Puskas"
                        },
                        new
                        {
                            ID = 8,
                            Email = "a20@uminho.pt",
                            Iban = "6003261",
                            Mbway = "937733894",
                            Password = "3131",
                            Rating = 10,
                            Username = "Eusébio"
                        });
                });

            modelBuilder.Entity("BeFeira.Shared.Carrinho", b =>
                {
                    b.HasOne("BeFeira.Shared.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteID");

                    b.HasOne("BeFeira.Shared.Stand", "Stand")
                        .WithMany()
                        .HasForeignKey("StandID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Stand");
                });

            modelBuilder.Entity("BeFeira.Shared.CarrinhoProduto", b =>
                {
                    b.HasOne("BeFeira.Shared.Carrinho", "Carrinho")
                        .WithMany()
                        .HasForeignKey("CarrinhoID");

                    b.HasOne("BeFeira.Shared.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoID");

                    b.Navigation("Carrinho");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("BeFeira.Shared.Produto", b =>
                {
                    b.HasOne("BeFeira.Shared.Stand", "Stand")
                        .WithMany()
                        .HasForeignKey("StandID");

                    b.HasOne("BeFeira.Shared.Subcategoria", "Subcategoria")
                        .WithMany()
                        .HasForeignKey("SubCategoriaID");

                    b.Navigation("Stand");

                    b.Navigation("Subcategoria");
                });

            modelBuilder.Entity("BeFeira.Shared.Promocao", b =>
                {
                    b.HasOne("BeFeira.Shared.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoID");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("BeFeira.Shared.Stand", b =>
                {
                    b.HasOne("BeFeira.Shared.Feira", "Feira")
                        .WithMany()
                        .HasForeignKey("FeiraID");

                    b.HasOne("BeFeira.Shared.Vendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorID");

                    b.Navigation("Feira");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("BeFeira.Shared.Subcategoria", b =>
                {
                    b.HasOne("BeFeira.Shared.Stand", "Stand")
                        .WithMany()
                        .HasForeignKey("StandID");

                    b.Navigation("Stand");
                });

            modelBuilder.Entity("BeFeira.Shared.Venda", b =>
                {
                    b.HasOne("BeFeira.Shared.Carrinho", "Carrinho")
                        .WithMany()
                        .HasForeignKey("CarrinhoID");

                    b.Navigation("Carrinho");
                });

            modelBuilder.Entity("BeFeira.Shared.VendaProduto", b =>
                {
                    b.HasOne("BeFeira.Shared.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoID");

                    b.HasOne("BeFeira.Shared.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("VendaID");

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });
#pragma warning restore 612, 618
        }
    }
}
